---
title: "2026 *Ulva australis* PAM -- Salinity analysis"
title-block-banner: true
date: today
date-format: "YYYY MMM MM"
author: 
  - name: Dai Sumiyoshi
  - name: Kaiki Tajiri
  - name: Masahiro Suzuki
  - name: Gregory N. Nishihara
  - name: Ryuta Terada
execute: 
  echo: false
  message: false
  warning: false
---

```{r}
#| include: false
library(tidyverse)
library(ggpubr)
library(ggtext)
library(magick)
library(patchwork)
library(showtext)
library(brms)
library(tidybayes)
library(gt)
library(gnnlab)
library(utils)
library(readxl)
```

```{r}
#| include: false
font_add_google("Noto Sans", family = "ns")
theme_pubr(10, "ns", border = TRUE) |> 
  set_theme()
theme_pubr() |> 
  replace_theme(
    axis.line.x = element_blank(),
    axis.line.y = element_blank(),
    axis.title.x = element_markdown(family = "ns", margin = margin(0.5, 0, 0.5, 0, "lines")),
    axis.title.y = element_markdown(family = "ns", angle= 90, margin = margin(0, 0.5, 0, 0.5, "lines")),
  )
showtext_auto()
folder = "~/Dropbox/MS_Terada_Greg/"
folder = "./Data/"
fnames = dir(folder, recursive = TRUE)
```


```{r}
ftext = "salinity"
fname = str_c(folder, str_subset(fnames, ftext)) 
esheets = excel_sheets(fname)
data = tibble(fname, esheets) |> 
  mutate(data = map2(fname, esheets, \(fname = fname, esheets = esheets) {
    read_xlsx(fname, sheet = esheets[1], range = "A1:M14") |>
      select(PSU, matches("Y\\(II\\)"))
  } )) |> 
  mutate(Days = str_extract(esheets, "[0-9]+")) |> 
  select(Days, data) |> 
  unnest(data) |> 
  pivot_longer(matches("^Y")) |> 
  mutate(ID = as.numeric(str_extract(name, "[0-9]+"))) |> 
  mutate(Days = factor(Days, levels = c("1", "3", "5", "7"))) |> 
  mutate(days = as.numeric(Days))

```

```{r}
xlabel = "Salinity (PSU)"
ylabel = "Effective quantum yield (&Delta;F/Fm&prime;)"
xbreaks = unique(data$PSU)
xbreaks = seq(0, 100, by = 20)
# 1. Create a label dataframe 
# We take distinct categories and generate the "A: ..." label here
labeldf = data |> expand(Days, x = min(PSU), y = 1) |> 
  mutate(
    l = str_glue("({LETTERS[seq_along(Days)]}) Incubation duration: {Days}-d ")
  )

p1 = ggplot(data) + 
  geom_point(aes(x = PSU, y = value), 
             position = position_jitter(width = 0.2), 
             shape = 21,
             fill = "black",
             stroke = 0,
             alpha = 0.8) +
  geom_richtext(aes(x = x, y = y, label = l),
                data = labeldf,
    vjust = 1, hjust = 0,
    color = "transparent",
    fill = "transparent",
    text.color = "black",
    family = "ns", 
    size = 3
  ) +
  scale_x_continuous(xlabel, breaks = xbreaks, limits = range(xbreaks)) +
  scale_y_continuous(ylabel, breaks = seq(0, 1, by = 0.25), limits = c(0, 1)) +
  facet_wrap(vars(Days), ncol = 2) +
  theme(
    strip.text = element_blank(),
    strip.background = element_blank()
  )

pdfname = "PAM-Salinity-plot.pdf"
save_plot(pdfname, plot = p1, width = 80 * 2, height = 80)
```



::: {#fig-pam-temp}


```{r}
image_read(str_replace(pdfname, "pdf", "png"))
```

The response of the effective quantum yield (&Delta; F/Fm&prime;) in the green alga, 
*Ulva australis* from Nagashima Island, Kagoshima, Japan.
The experiments were conducted at salinity treatments of 0 to 100 PSU  
after 1, 3, 5, and 7 days of incubation at 16 &deg;C and
20 &mu;mol photons m^-2^ s^-1^ and a 12L12D photoperiod.
The points are jittered horizontally for clarity (n = 10).
:::



```{r}
cores = chains = 5
seed = 2026
warmup = 400
iterations = warmup + 1000
file_refit = "always"
control = list(adapt_delta = 0.995, max_treedepth = 15)
filename_null = "pam-salinity-null-model"
filename_full = "pam-salinity-full-model"

fullmodel = bf(
  value ~ t2(salinity, PSU, k = c(4, 10), bs = "cr"),
  phi ~ s(PSU, k = 10, bs = "cr")
  ) +   Beta()

# get_prior(nullmodel, data)
# get_prior(fullmodel, data)
priors_null = c(
  prior(student_t(3, 0, 2.5), class = Intercept),
  prior(student_t(3, 0, 2.5), class = b),
  prior(student_t(3, 0, 2.5), class = sds),
  prior(student_t(3, 0, 2.5), dpar = zi, class = Intercept),
  prior(student_t(3, 0, 2.5), dpar = zi, class = b),
  prior(student_t(3, 0, 2.5), dpar = zi, class = sds),
  prior(gamma(0.01, 0.01), class = phi)
)
priors_full = c(
  prior(student_t(3, 0, 2.5), class = Intercept),
  prior(student_t(3, 0, 2.5), class = b),
  prior(student_t(3, 0, 2.5), class = sds),
  prior(student_t(3, 0, 2.5), dpar = zi, class = Intercept),
  prior(student_t(3, 0, 2.5), dpar = zi, class = b),
  prior(student_t(3, 0, 2.5), dpar = zi, class = sds),
  prior(gamma(0.01, 0.01), class = phi)
)
```


```{r}
#| label: nullmodel

plan(cluster, workers = "mimir")
futurenull = future({
  brm(
    nullmodel,
    data = data,
    prior = priors_null,
    chains = chains,
    cores = cores,
    seed = seed,
    iter = iterations,
    warmup = warmup,
    refresh = 0,
    file = filename_null,
    file_refit = file_refit,
    backend = "cmdstanr",
    threads = threading(4),
    control = control,
    save_pars = save_pars(all = TRUE)
  )
})

z = 0
while(!resolved(futurenull)) {
  z0 = lubridate::now()
  message("Model is still sampling... ", z0)
  Sys.sleep(10) # Check every 10 seconds
  z = z + 10
}

message("Done! You can now run: fit <- value(futurenull)\n", "Total time is: ", z/60, " minutes.")
plan(sequential)
```

```{r}
bout_null = value(futurenull)

require(ssh)
remote = str_c("/home/gnishihara/MS_Terada_Nishihara_ulva_australis_202601/", filename_null, ".rds") |> print()
session = ssh_connect("mimir")
scp_download(session, files = remote, to = "./")
ssh_disconnect(session)
```
